##
# Feeds

-
  name: feed
  uriPattern: rss.xml
  defaults:
    '@controller': Standard
    '@action': feed
    '@format': xml
  appendExceedingArguments: true

##
# Default route

-
  name: fallback
  uriPattern: ''
  defaults:
    '@controller': Standard
    '@action': index
  appendExceedingArguments: true
