##
# Feeds

-
  name: 'feed'
  uriPattern: 'rss.xml'
  defaults:
    '@package':    'Planetflow3'
    '@controller': 'Standard'
    '@action':     'feed'
    '@format':     'xml'

##
# Default route

-
  name: 'fallback'
  uriPattern: ''
  defaults:
    '@package':    'Planetflow3'
    '@controller': 'Standard'
    '@action':     'index'
    '@format':     'html'
